from __future__ import annotations

import base64
import json
import re
from dataclasses import dataclass
from pathlib import PurePosixPath

from .github import GitHubClient, GitHubIssue
from .model_gateway import ModelGateway


@dataclass(frozen=True)
class FileChange:
    path: str
    content: str


class ChangeRejected(ValueError):
    pass


class DeveloperAgentService:
    """Turns an Issue into a guarded branch and PR; it never merges."""

    BLOCKED_PREFIXES = (".github/workflows/", ".git/", ".agentic/")
    BLOCKED_NAMES = {".env", "CODEOWNERS"}
    BRANCH_RE = re.compile(r"[^a-zA-Z0-9._/-]+")

    def __init__(self, github: GitHubClient, model: ModelGateway, *,
                 allowed_prefixes: tuple[str, ...] = ("src/", "tests/", "docs/"),
                 max_files: int = 5, max_chars: int = 50000):
        self.github = github
        self.model = model
        self.allowed_prefixes = allowed_prefixes
        self.max_files = max_files
        self.max_chars = max_chars

    def propose(self, issue: GitHubIssue) -> tuple[str, list[FileChange]]:
        response = self.model.complete(
            "Return JSON only: {summary:string, files:[{path:string, content:string}]}. "
            "Implement the smallest testable change. Never edit workflows, secrets or policy.",
            issue.body,
            {"task": "developer.change", "issue": issue.number, "title": issue.title},
        )
        data = json.loads(response.content)
        changes = [FileChange(path=item["path"], content=item["content"]) for item in data["files"]]
        self._validate(changes)
        return str(data["summary"]), changes

    def _validate(self, changes: list[FileChange]) -> None:
        if not changes or len(changes) > self.max_files:
            raise ChangeRejected("invalid file count")
        if sum(len(item.content) for item in changes) > self.max_chars:
            raise ChangeRejected("change exceeds size budget")
        for item in changes:
            path = PurePosixPath(item.path)
            normalized = str(path)
            if path.is_absolute() or ".." in path.parts:
                raise ChangeRejected("path traversal is forbidden")
            if normalized in self.BLOCKED_NAMES or normalized.startswith(self.BLOCKED_PREFIXES):
                raise ChangeRejected("sensitive path is forbidden")
            if not normalized.startswith(self.allowed_prefixes):
                raise ChangeRejected("path is outside developer scope")

    def implement(self, issue_number: int, *, base_branch: str = "master") -> dict:
        issue = self.github.get_issue(issue_number)
        summary, changes = self.propose(issue)
        branch = self.BRANCH_RE.sub("-", f"agent/issue-{issue.number}-{summary.lower()}")[:100].strip("-")
        repo = self.github.repository
        base = self.github._request("GET", f"/repos/{repo}/git/ref/heads/{base_branch}")
        self.github._request("POST", f"/repos/{repo}/git/refs", {
            "ref": f"refs/heads/{branch}", "sha": base["object"]["sha"],
        })
        changed_paths = []
        for change in changes:
            current = None
            try:
                current = self.github._request(
                    "GET", f"/repos/{repo}/contents/{change.path}?ref={base_branch}"
                )
            except RuntimeError as error:
                if "404" not in str(error):
                    raise
            payload = {
                "message": f"feat: issue #{issue.number} {summary}",
                "content": base64.b64encode(change.content.encode()).decode(),
                "branch": branch,
            }
            if current:
                payload["sha"] = current["sha"]
            self.github._request("PUT", f"/repos/{repo}/contents/{change.path}", payload)
            changed_paths.append(change.path)
        pr = self.github._request("POST", f"/repos/{repo}/pulls", {
            "title": f"feat: {summary}",
            "head": branch, "base": base_branch,
            "body": f"Implements #{issue.number}.\n\nGenerated by Developer Agent. Human review required.",
            "draft": True,
        })
        self.github.comment(issue.number, f"Developer Agent abriu o draft PR: {pr['html_url']}")
        return {"branch": branch, "pull_request": pr["html_url"], "files": changed_paths, "merged": False}
